module.exports = {
  activedesactiveParticipations: require('./activedesactiveParticipation'),
  activeShopOffers: require('./activeShopOffers'),
  actualAvatar: require('./actualavatar'),
  actualquest: require('./actualquest'),
  announcement: require('./announcement'),
  announcementChannel: require('./announcementChannel.js'),
  avatarPlayer: require('./avatarplayer'),
  battlepassChallenges: require('./battlepassChallenges'),
  botInfo: require('./botInfo'),
  changeFlair: require('./changeFlair'),
  clanMembers: require('./clanmembers'),
  commandList: require('./commandList'),
  deleteOldMessages: require('./deleteOldMessages').deleteOldMessages,
    scheduleMidnightTask: require('./deleteOldMessages').scheduleMidnightTask,
    resetDailyDeletedMessages: require('./deleteOldMessages').resetDailyDeletedMessages,
  easterEggs: require('./easterEggs'),
  getAdvancedRoles: require('./getAdvancedRoles'),
  getApiHat: require('./getApiHat'),
  getClanId: require('./getClanId'),
  getClanInfo: require('./getinfoclan'),
  idAvatar: require('./idAvatar'),
  infoRole: require('./infoRole'),
  playerCards: require('./playerCards'),
  playerProfil: require('./playerProfil'),
  playerStats: require('./playerStats'),
  questAvailable: require('./questavalaible'),
  checkQuestStatus: require('./questChannel'),
  roleRotations: require('./roleRotations'),
  searchAvatarId: require('./searchAvatarId'),
  checkClanChat: require('./syncchat').checkClanChat,
  sendToWolvesville: require('./syncchat').sendToWolvesville,
  handleDiscordMessage: require('./syncchat').handleDiscordMessage,
  // Delete sendMessage here to disable sendMessage feature
  sendMessage: require('./sendMessage').sendMessage,
};