const actualquest = require('./actualquest');

module.exports = {
  avatarPlayer: require('./avatarplayer'),
  actualAvatar: require('./actualavatar'),
  questAvailable: require('./questavalaible'),
  announcement: require('./announcement'),
  clanMembers: require('./clanmembers'),
  getClanId: require('./getclanId'),
  getClanInfo: require('./getinfoclan'),
  playerStats: require('./playerStats'),
  playerCards: require('./playerCards'),
  playerProfil: require('./playerProfil'),
  infoRole: require('./infoRole'),
  getAdvancedRoles: require('./getAdvancedRoles'),
  activeShopOffers: require('./activeShopOffers'),
  battlepassChallenges: require('./battlepassChallenges'),
  roleRotations: require('./roleRotations'),
  idAvatar: require('./idAvatar'),
  searchAvatarId: require('./searchAvatarId'),
  getApiHat: require('./getApiHat'),
  botInfo: require('./botInfo'),
  commandList: require('./commandList'),
  easterEggs: require('./easterEggs'),
  checkClanChat: require('./syncchat').checkClanChat,
  sendToWolvesville: require('./syncchat').sendToWolvesville,
  handleDiscordMessage: require('./syncchat').handleDiscordMessage,
  deleteOldMessages: require('./deleteOldMessages').deleteOldMessages,
  scheduleMidnightTask: require('./deleteOldMessages').scheduleMidnightTask,
  resetDailyDeletedMessages: require('./deleteOldMessages').resetDailyDeletedMessages,
  actualquest: require('./actualquest'),
  checkQuestStatus: require('./questChannel'),
};