const { triggerDailyScreenTime } = require('../tasks/screenTimeTask.js');

module.exports = {
  changeParticipations: require('../commands/leaders/changeParticipations.js'),
  activeShopOffers: require('../commands/members/shop/activeShopOffers.js'),
  actualAvatar: require('../commands/members/player/actualAvatar.js'),
  actualQuest: require('../commands/members/quests/actualQuest.js'),
  announcement: require('../commands/members/clan/announcement.js'),
  announcementChannel: require('../events/announcementChannel.js').announcementChannel,
  loadAnnouncementsFromDB: require('../events/announcementChannel.js').loadAnnouncementsFromDB,
  avatarPlayer: require('../commands/members/player/avatarPlayer.js'),
  battlepassChallenges: require('../commands/members/shop/battlepassChallenges.js'),
  botInfo: require('../commands/members/bot/botInfo.js'),
  changeFlair: require('../commands/leaders/changeFlair.js'),
  clanMembers: require('../commands/members/clan/clanMembers.js'),
  commandList: require('../commands/members/bot/commandList.js'),
  deleteOldMessages: require('../tasks/deleteOldMessages.js'),
  easterEggs: require('../commands/members/easterEggs.js'),
  getAdvancedRoles: require('../commands/members/roles/getAdvancedRoles.js'),
  getApiHat: require('../commands/members/player/getApiHat.js'),
  getClanId: require('../commands/members/clan/getClanId.js'),
  getClanInfo: require('../commands/members/clan/getInfoClan.js'),
  idAvatar: require('../commands/members/player/idAvatar.js'),
  infoRole: require('../commands/members/roles/infoRole.js'),
  leadersCommandsInfo: require('../commands/leaders/leadersCommandsInfo.js'),
  playerCards: require('../commands/members/player/playerCards.js'),
  playerProfil: require('../commands/members/player/playerProfil.js'),
  playerStats: require('../commands/members/player/playerStats.js'),
  postAnnouncement: require('../tasks/postAnnouncement.js'),
  questAvailable: require('../commands/members/quests/questAvailable.js'),
  checkQuestStatus: require('../events/checkQuestStatus.js'),
  roleRotations: require('../commands/members/roles/roleRotations.js'),
  scheduleDailyTask: require('../tasks/scheduleDailyTask.js'),
  mondayAnnouncementTask: require('../tasks/mondayAnnouncementTask.js'),
  searchAvatarId: require('../commands/members/player/searchAvatarId.js'),
  checkClanChat: require('../events/syncChat.js').checkClanChat,
  loadLastSeenDateFromDB: require('../events/syncChat.js').loadLastSeenDateFromDB,
  sendToWolvesville: require('../events/syncChat.js').sendToWolvesville,
  handleDiscordMessage: require('../events/syncChat.js').handleDiscordMessage,
  toggleMondayQuest: require('../commands/leaders/toggleMondayQuest.js'),
  toggleGemQuests: require('../commands/leaders/toggleGemQuests.js'),
  sendQuestAnnouncement: require('../commands/leaders/sendQuestAnnouncement.js'),
  findBestQuest: require('../utils/findBestQuest.js'),
  executeQuestAnnouncement: require('../tasks/executeQuestAnnouncement.js'),
  mondayQuestAnnouncementTask: require('../tasks/mondayQuestAnnouncementTask.js'),
  getSpecificQuest: require('../utils/getSpecificQuest.js'),
  syncClanMembers: require('../tasks/syncClanMembers.js'),
  setNickname: require('../commands/leaders/setNickname.js'),
  findPlayer: require('../utils/findPlayer.js'),

  // Delete sendMessage here to disable sendMessage feature
  sendMessage: require('../events/sendMessage.js').sendMessage,
  triggerDailyScreenTime: require('../tasks/screenTimeTask.js').triggerDailyScreenTime,
  setupScreenTimeListener: require('../tasks/screenTimeTask.js').setupScreenTimeListener,
  checkScreenTimeReminder: require('../tasks/screenTimeTask.js').checkScreenTimeReminder
};