module.exports = {
  activedesactiveParticipations: require('./commands/leaders/activedesactiveParticipation.js'),
  activeShopOffers: require('./commands/members/shop/activeShopOffers.js'),
  actualAvatar: require('./commands/members/player/actualavatar.js'),
  actualquest: require('./commands/members/quests/actualquest.js'),
  announcement: require('./commands/members/clan/announcement.js'),
  announcementChannel: require('./events/announcementChannel.js'),
  avatarPlayer: require('./commands/members/player/avatarplayer.js'),
  battlepassChallenges: require('./commands/members/shop/battlepassChallenges.js'),
  botInfo: require('./commands/members/bot/botInfo.js'),
  changeFlair: require('./commands/leaders/changeFlair.js'),
  clanMembers: require('./commands/members/clan/clanmembers.js'),
  commandList: require('./commands/members/bot/commandList.js'),
  deleteOldMessages: require('./tasks/deleteOldMessages.js').deleteOldMessages,
    resetDailyDeletedMessages: require('./tasks/deleteOldMessages.js').resetDailyDeletedMessages,
  easterEggs: require('./commands/members/easterEggs.js'),
  getAdvancedRoles: require('./commands/members/roles/getAdvancedRoles.js'),
  getApiHat: require('./commands/members/player/getApiHat.js'),
  getClanId: require('./commands/members/clan/getclanId.js'),
  getClanInfo: require('./commands/members/clan/getinfoclan.js'),
  idAvatar: require('./commands/members/player/idAvatar.js'),
  infoRole: require('./commands/members/roles/infoRole.js'),
  playerCards: require('./commands/members/player/playerCards.js'),
  playerProfil: require('./commands/members/player/playerProfil.js'),
  playerStats: require('./commands/members/player/playerStats.js'),
  postAnnouncement: require('./tasks/postAnnouncement.js'),
  questAvailable: require('./commands/members/quests/questavalaible.js'),
  checkQuestStatus: require('./events/questChannel.js'),
  roleRotations: require('./commands/members/roles/roleRotations.js'),
  scheduleDailyTask: require('./tasks/task.js').scheduleDailyTask,
  mondayAnnouncementTask: require('./tasks/task.js').mondayAnnouncementTask,
  searchAvatarId: require('./commands/members/player/searchAvatarId.js'),
  checkClanChat: require('./events/syncchat.js').checkClanChat,
  sendToWolvesville: require('./events/syncchat.js').sendToWolvesville,
  handleDiscordMessage: require('./events/syncchat.js').handleDiscordMessage,
  // Delete sendMessage here to disable sendMessage feature
  sendMessage: require('./events/sendMessage.js').sendMessage,
};